package br.com.ifpb.tipos;

public enum TipoCertidao {

	CERTIDAO_NEGATIVA_ESTADUAL, CERTIDAO_NEGATIVA_TRABALHISTA, CERTIDAO_NEGATIVA_FEDERAL, CERTIDAO_NEGATIVA_MUNICIPAL, 
	CERTIDAO_NEGATIVA_CAIXA;
	
}
